--SELECT OGRAD,DERSORT.DERSAD,SINAV1,SINAV1ORT,
--CASE
--	WHEN SINAV1ORT>SINAV1 THEN 'ORTALAMA ALTI'
--	WHEN SINAV1ORT=SINAV1 THEN 'ORTALAMA'
--	WHEN SINAV1ORT<SINAV1 THEN 'ORTALAMA USTU'
--END AS SINAV1DURUM
--FROM TBLOGRENCILER
--INNER JOIN TBLNOTLAR ON TBLOGRENCILER.OGRID=TBLNOTLAR.OGRENCI
--INNER JOIN TBLDERSLER ON TBLDERSLER.DERSID=TBLNOTLAR.DERS 
--INNER JOIN
--(SELECT DERSAD,AVG(SINAV1) AS 'SINAV1ORT' FROM TBLNOTLAR INNER JOIN TBLDERSLER ON TBLDERSLER.DERSID=TBLNOTLAR.DERS GROUP BY DERSAD) AS DERSORT 
--ON TBLDERSLER.DERSAD=DERSORT.DERSAD 




--WHERE OGRAD='AYSE'

SELECT OGRAD,OGRSOYAD,SINAV1,SINAV1ORT,

CASE 
	WHEN SINAV1ORT<SINAV1 THEN'ORTALAMA USTU'
	WHEN SINAV1ORT>=SINAV1 THEN 'ORTALAMA ALTI'
	END AS SINAV1DURUM

	FROM TBLOGRENCILER 
INNER JOIN TBLNOTLAR ON TBLOGRENCILER.OGRID=TBLNOTLAR.OGRENCI
INNER JOIN TBLDERSLER ON TBLDERSLER.DERSID=TBLNOTLAR.DERS
INNER JOIN
(SELECT DERSAD,AVG(SINAV1) AS 'SINAV1ORT' FROM TBLNOTLAR INNER JOIN TBLDERSLER ON TBLDERSLER.DERSID=TBLNOTLAR.DERS GROUP BY DERSAD) AS DERSORT
ON TBLDERSLER.DERSAD=DERSORT.DERSAD

WHERE OGRAD='AYSE'
